<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <AssemblyName>Flow.Launcher.Plugin.PowerToys</AssemblyName>
    <PackageId>Flow.Launcher.Plugin.PowerToys</PackageId>
    <Authors>PederBirk</Authors>
    <PackageProjectUrl>https://github.com/PederBirk/Flow.Launcher.Plugin.PowerToys</PackageProjectUrl>
    <RepositoryUrl>https://github.com/PederBirk/Flow.Launcher.Plugin.PowerToys</RepositoryUrl>
    <PackageTags>flow-launcher flow-plugin</PackageTags>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>12</LangVersion>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
    <NoWarn>1701;1702;1591;FLSG0007</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
    <NoWarn>1701;1702;1591;FLSG0007</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591;FLSG0007</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <NoWarn>1701;1702;1591;FLSG0007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="plugin.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Flow.Launcher.Localization" Version="0.0.5" />
    <PackageReference Include="Flow.Launcher.Plugin" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="images\PowerToys.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
	<Content Include="Languages\**">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</Content>
  </ItemGroup>

  <ItemGroup>
	<Content Update="Languages\en.xaml">
		<Generator>MSBuild:Compile</Generator>
	</Content>
    <Content Update="Languages\zh-cn.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Content>
  </ItemGroup>

</Project>
