name: build

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      NTFY_URL: ${{ secrets.NTFY_URL }}
      NTFY_TOKEN: ${{ secrets.NTFY_TOKEN }}
      NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Get tags
        id: git_tags
        run: |
          current=$(git describe --abbrev=0 --tags)
          echo "current=${current}" >> ${GITHUB_OUTPUT}
        shell: bash

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet publish -c Release -r win-x64 --no-self-contained Flow.Launcher.Plugin.PowerToys.csproj
          7z a -tzip "Flow.Launcher.Plugin.PowerToys.zip" "./bin/Release/win-x64/publish/*"

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: 'Flow.Launcher.Plugin.PowerToys.zip'
          tag_name: ${{ steps.git_tags.outputs.current }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send notification
        if: ${{ !cancelled() && env.NTFY_URL != '' && env.NTFY_TOKEN != '' && env.NTFY_TOPIC != '' }}
        uses: dragonish/send-to-ntfy@v1
        with:
          base-url: ${{ secrets.NTFY_URL }}
          topic: ${{ secrets.NTFY_TOPIC }}
          access-token: ${{ secrets.NTFY_TOKEN }}
          title: ${{ github.repository }}
          message: 'Build ${{ steps.git_tags.outputs.current }}'
          tags: 'GitHub,building_construction,${{ job.status }}'
          priority: 2
          click: 'https://github.com/${{ github.repository }}/releases/tag/${{ steps.git_tags.outputs.current }}'
