name: build

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Get tags
        id: git_tags
        run: |
          current=$(git describe --abbrev=0 --tags)
          echo "current=${current}" >> ${GITHUB_OUTPUT}
        shell: bash

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet publish -c Release -r win-x64 --no-self-contained Flow.Launcher.Plugin.PowerToys.csproj
          7z a -tzip "Flow.Launcher.Plugin.PowerToys.zip" "./bin/Release/win-x64/publish/*"

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: 'Flow.Launcher.Plugin.PowerToys.zip'
          tag_name: ${{ steps.git_tags.outputs.current }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
